export interface Customer {
  id?: string; // Optional because it's generated by the database
  name: string;
  email: string;
  phone?: string;
  createdAt?: Date; // Optional as it can be set by the database or application
  updatedAt?: Date; // Optional as it can be set by the database or application
}